# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure("2") do |config|
    
    config.vm.box = "centos/8"
    
    (1..2).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.hostname = "node-#{i}"
            # node.vm.provision "shell",
            #     inline: "echo hello from node #{i}"

            node.vm.provision "shell", inline: <<-SHELL
               echo hello from node #{i}
            SHELL

            node.vm.network "public_network", ip: "192.168.42.11#{i}", hostname: true, bridge: "enp0s20f0u1"
        end
    end
end